CREATE UNIQUE INDEX INSIS_CUST.ADDRESSDATADDIT_PK ON INSIS_CUST.P_ADDRESS_DATA_ADDIT
(ID)
TABLESPACE INDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/