ALTER TABLE INSIS_CUST.AUP_BORDEROUX_FILE ADD (
  CONSTRAINT AUP_BORDERO_STATE_CH
  CHECK (state IN ('I', 'E', 'P')
)
  DISABLE NOVALIDATE
,  CONSTRAINT AUP_BORDEROUX_FILE_UNQ1
  UNIQUE (RECORD_ID)
  USING INDEX INSIS_CUST.AUP_BORDEROUX_FILE_UNQ1
  ENABLE VALIDATE
,  CONSTRAINT AUP_BORDEROUX_FILE_UNQ2
  UNIQUE (COLLECTION_ID, FILE_NAME)
  USING INDEX INSIS_CUST.AUP_BORDEROUX_FILE_UNQ2
  ENABLE VALIDATE)
/