CREATE OR REPLACE TYPE BODY INSIS_CUST."CCM_ANNEX_AS_APLA_HLT" AS
  CONSTRUCTOR FUNCTION CCM_ANNEX_AS_APLA_HLT(SELF IN OUT NOCOPY CCM_ANNEX_AS_APLA_HLT) RETURN SELF AS RESULT AS
  BEGIN
    SELF.CAUSAAPLAZAMIENTO   := 'NULL';  
    SELF.PERIODOAPLAZAMIENTO := 'NULL';                 
    RETURN;
  END CCM_ANNEX_AS_APLA_HLT;

  CONSTRUCTOR FUNCTION CCM_ANNEX_AS_APLA_HLT(SELF IN OUT NOCOPY CCM_ANNEX_AS_APLA_HLT, 
                                                                CAUSAAPLAZAMIENTO VARCHAR2,
                                                                PERIODOAPLAZAMIENTO VARCHAR2
                        ) RETURN SELF AS RESULT AS
  BEGIN
    SELF.CAUSAAPLAZAMIENTO   := NVL(CAUSAAPLAZAMIENTO,   'NULL');
    SELF.PERIODOAPLAZAMIENTO := NVL(PERIODOAPLAZAMIENTO, 'NULL');                            
    RETURN;
  END CCM_ANNEX_AS_APLA_HLT;

END;

/