CREATE OR REPLACE FUNCTION INSIS_CUST.CUST_SET_IV_FIANZAS 
(
POLICY_ID_IN IN NUMBER,
ANNEX_ID_IN IN NUMBER
) RETURN NUMBER

IS

COVER_CUMP NUMBER;
COVER_FIA NUMBER;
RESULTADO NUMBER;
OBJECT VARCHAR2 (10 BYTE);

BEGIN

SELECT LIAB_TYPE INTO OBJECT
FROM O_LIABILITY
WHERE OBJECT_ID =
(
SELECT OBJECT_ID
FROM INSURED_OBJECT
WHERE POLICY_ID = POLICY_ID_IN
AND ANNEX_ID = ANNEX_ID
);

select sum (INSURED_VALUE) INTO COVER_CUMP
FROM GEN_RISK_COVERED
WHERE POLICY_ID = POLICY_ID_IN
AND ANNEX_ID = ANNEX_ID_IN
AND (COVER_TYPE = 'CUMCONT' OR COVER_TYPE = 'MANT' OR COVER_TYPE = 'VICIO');

SELECT MAX (INSURED_VALUE) INTO COVER_FIA
FROM GEN_RISK_COVERED
WHERE POLICY_ID = POLICY_ID_IN
AND ANNEX_ID = ANNEX_ID_IN;

IF OBJECT = 'FRCCON'
THEN RESULTADO := COVER_CUMP;
ELSE RESULTADO := COVER_FIA;
END IF;

  RETURN RESULTADO;
END CUST_SET_IV_FIANZAS;
/